name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Vet
        run: go vet github.com/greatliontech/gomutant/...

      - name: gofmt check
        run: test -z "$(gofmt -l . | grep -v testdata)"

      - name: Tidy check
        run: go mod tidy -diff

      - name: Test
        run: go test -race github.com/greatliontech/gomutant/...
